Update veracode-template.yml

diff --git a/.github/workflows/veracode-template.yml b/.github/workflows/veracode-template.yml
--- a/.github/workflows/veracode-template.yml
+++ b/.github/workflows/veracode-template.yml
@@ -15,16 +15,7 @@ jobs:
           echo "🛠️ Verificando ambiente..."
           uname -a
           echo "✅ Ambiente pronto."
-          
-  Veracode_SCA:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-      - name: Veracode SCA
-        env:
-          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }} # Lembrar de criar as credenciais no Secrets
-        run: |
-          curl -sSL 'https://download.sourceclear.com/ci.sh' | bash -s – scan --update-advisor --pull-request --allow-dirty
+        
   
   autopack:
     needs: environment-check
@@ -66,7 +57,27 @@ jobs:
         uses: actions/upload-artifact@v3
         with:
           name: analysisPack
-          path: $ARTIFACTS_DIR/artifacts/analysisPack.zip
+          path: ./artifacts/analysisPack.zip
+
+      - name: Validar Pacote Gerado
+        run: |
+          if [ -f "./artifacts/analysisPack.zip" ]; then
+            echo "✅ Arquivo encontrado: ./artifacts/analysisPack.zip"
+          else
+            echo "❌ Arquivo não encontrado. Abortando."
+            exit 1
+          fi
+
+  Veracode_SCA:
+    needs: autopack
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Veracode SCA
+        env:
+          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }} # Lembrar de criar as credenciais no Secrets
+        run: |
+          curl -sSL 'https://download.sourceclear.com/ci.sh' | bash -s – scan --update-advisor --pull-request --allow-dirty         
 
   veracode-sast-pipeline_scan:
     needs: autopack
@@ -74,10 +85,10 @@ jobs:
     name: veracode pipeline scan
 
     steps:
-      - name: checkout repo
+      - name: checkout
         uses: actions/checkout@v4
       
-      - name: get archive
+      - name: download do artefato
         uses: actions/download-artifact@v3
         with:
           name: analysisPack
